"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 5.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.0/ref/settings/
"""

import os
from pathlib import Path
from datetime import timedelta
from dotenv import load_dotenv
from google.oauth2 import service_account
from google.cloud import dialogflow_v2 as dialogflow

load_dotenv()  # Loads environment variables from .env file

BASE_DIR = Path(__file__).resolve().parent.parent

GOOGLE_PROJECT_ID = os.getenv('GOOGLE_PROJECT_ID')
DIALOGFLOW_SESSION_ID = os.getenv('DIALOGFLOW_SESSION_ID')
DIALOGFLOW_SESSION_LANGUAGE_CODE = os.getenv('DIALOGFLOW_SESSION_LANGUAGE_CODE')
GOOGLE_CLIENT_EMAIL = os.getenv('GOOGLE_CLIENT_EMAIL')
GOOGLE_PRIVATE_KEY = os.getenv('GOOGLE_PRIVATE_KEY').replace('\\n', '\n')
MONGO_URI = os.getenv('MONGO_URI')
JWT_SECRET = os.getenv('JWT_SECRET')
ADMIN_GOOGLE_CLIENT_EMAIL = os.getenv('ADMIN_GOOGLE_CLIENT_EMAIL')
ADMIN_GOOGLE_PRIVATE_KEY = """-----BEGIN PRIVATE KEY-----
MIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQDjpeeuPlQOuq6f
6BycUWHElv6UkdxdWnoBbqMj3xnBIqd0Eja/jBdmwMF9Be3i3fcu9n0aa7VxX30f
u/36QuILmqsGhhCpl2L8+jDKkNXpBfvjUnucUdBIFkYBk/RApC0isVnvK8D9iwKB
dD+0JFqWtZo8LxViEzFB+e1x/k3VR3PFnz6je8VqLhNRwLhYkNBit/+2loZNsyHY
9MByAiaUAKVrkzLup/2lCqOdIIONXExQnoi7vDk928xY2d3Bv+MRClIyZbBLRXij
797h/OrNvLzDsSia3fRMrqcdb0wogoVKg4Ckoou3q+oxRvHLPb52Ny9NOpKxEfFe
IjKlbTPNAgMBAAECggEADZsQ5lYwJhjhuXRrtgBbgx6m1LXasWioLJWSd2EiPqu7
IuHjdvN2QuxSfs3/1QSWUq6lilKgK528/SHPpj62Qw0e23sKnBGMd26zmP5q49cO
ojGVP4yYkcplAOX5HfOXWqtguD2e9qMG3A+uLq59NznfipPM0nRaXWVaMUCKodcb
IvvUf/yiCMn5rhJcf0k7E9dOZg/ZrDSLdLN3YXzshq2jO2MKvfIQwQdT7ViphgAE
LATqEKupo/SPTOvJ6/+F0iunccGS95STDPY+l7v01hBFaGXjDEy9QjN8k3nEZ8ga
XC5J57stnTzzvuFWy25hOwFxJX0V9egCHOyvjpMpKQKBgQDz3w/f9Kp07CH5ICkU
mXLI0N4M7IXdpuyGTNQYwc269RY5TDvydHuMKP7cS3E8Z2cjpikHyM9jXe48wVmz
uzjFSgJ9Ma1agbjMwjKHIzmFjLw6TorgklslELjQ2K7AGLqMSKgv4GTLCRur13kt
2U/g560+a6C5WlGX5rfUqq2fxQKBgQDu+EpadoOrFUBUmTbJQfFW4cDKt6lbVdfx
rZAiH021F6A1lHiJo+7txwygLMSnJHZ1HZHboH/2T8NuoY3uo+xZwfH6kUX7o2ZX
b/+L3oNO0C1PATaXc8VpFC9jUWodNkrirK+lRcY+4cF/OUFxN6jhg1GZJ3mLPLVb
dXT/83q8aQKBgQDeklWlu2Ia5iw3d5+mmknFd8NBHlkqq58xD0t/8Nk36VlIIAiS
Rrc/e2bnXb9SNrlOMuc9oIuOj/rP3lNlEtlETkCpTD5/3ObxkceVyJNGDOT5fheH
0Gt5D6LtkOUkky0mvWUqlOzI1V443qZNLwmVJTzbPFVq9UCEl2BtqvxdVQKBgQCe
VMf+1BM9IWF0K+eOxTBAHmd8aN++8kuXhyW+VftIhxTRK0QJ/iHqTT3iSocpLxGF
W0guulLOQd78x/GgMeABQG0xVVuG9KZ0PHKWm6FocKn0dJtVEZG0o3kaVvD11ekb
8sqVuHs3YqCvyKHBf91XPYis7uirBlgq9tHEW+/wMQKBgBypPdHYMDSCDx653G/b
298PN1YoT2cYdfstJIBpQ/5IYBoCe0CHMT9Pcl6X2hF6LmrcgbSNgVyWCXqhrGQb
bfmOCgDYf+wDd0ni47Y3x+YAc5hQPl8/OFoiu/6qOx9bJfU5yyXt+bIivejT9R2I
52VG5ptQhtgZgTkT730tuwbh
-----END PRIVATE KEY-----"""
# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-0(lkz%-&m^)ow+n&vk=se9!@rg@2#&gu3pe6&40_q-j)wvbltj'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'UIC.localhost', 'school1.localhost', 'uic.localhost', 'school1.localhost:3000']

# Django REST framework settings
REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': (
        'rest_framework.renderers.JSONRenderer',
    ),
    'DEFAULT_PARSER_CLASSES': (
        'rest_framework.parsers.JSONParser',
    ),
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.AllowAny',  # Require authentication by default
    ),
}

# JWT settings
SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=5),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=1),
    'ROTATE_REFRESH_TOKENS': True,
    'BLACKLIST_AFTER_ROTATION': True,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

# CORS settings
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://school1.localhost:3000",  # Add tenant-specific domains here
    "http://school1.localhost:8000",
    "http://uic.localhost:8000",  # Add tenant-specific domains here
    "http://uic.localhost:3000",
]
CORS_ALLOW_HEADERS = [
    "accept",
    "accept-encoding",
    "authorization",
    "content-type",
    "dnt",
    "origin",
    "user-agent",
    "x-csrftoken",
    "x-requested-with",
]

CORS_ALLOW_METHODS = [
    'GET',
    'POST',
    'PUT',
    'PATCH',
    'DELETE',
    'OPTIONS',
]
CORS_ALLOW_CREDENTIALS = True 

# CSRF settings
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:3000",
    "http://127.0.0.1:3000",
    "http://school1.localhost:3000",
    "http://uic.localhost:3000",
]

# Applications listed in SHARED_APPS will be synced to the public schema
# SHARED_APPS
SHARED_APPS = (
    'django_tenants',  # mandatory
    'django.contrib.contenttypes',  # mandatory

    # Add any other apps that should be available to all tenants
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'custom_auth', 
    'corsheaders',  # Your custom app should be here
    # any other shared apps
)

# TENANT_APPS
TENANT_APPS = (
    # Do not repeat 'django.contrib.contenttypes' here
    # Tenant-specific apps
    'django.contrib.auth',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'custom_auth',  # Include here as well for tenant-specific operations
)

# Combine shared and tenant apps, removing duplicates
INSTALLED_APPS = list(SHARED_APPS) + [app for app in TENANT_APPS if app not in SHARED_APPS]

# Tenant configurations
TENANT_MODEL = "custom_auth.Client"  # app.Model
TENANT_DOMAIN_MODEL = "custom_auth.Domain"  # app.Model

# Logging configuration
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'DEBUG',
    },
}

# Middleware configuration
MIDDLEWARE = [
    'django_tenants.middleware.main.TenantMainMiddleware',  # Must be first
    'corsheaders.middleware.CorsMiddleware',  # Handles CORS
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'custom_auth.middleware.SchemaLoggerMiddleware',
]

ROOT_URLCONF = 'backend.urls'

# Template configuration
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'backend.wsgi.application'

# Authentication backends
AUTHENTICATION_BACKENDS = [
    'custom_auth.authentication.CustomAuthBackend',
    'django.contrib.auth.backends.ModelBackend',
]

# Custom user model
AUTH_USER_MODEL = 'custom_auth.User'

# Database configuration
# https://docs.djangoproject.com/en/5.0/ref/settings/#databases
DATABASES = {
    'default': {
        'ENGINE': 'django_tenants.postgresql_backend',
        'NAME': 'ANNA',
        'USER': 'postgres',
        'PASSWORD': '1234',
        'HOST': 'localhost',  # or your database server address
        'PORT': '5432',  # default PostgreSQL port
    }
}

DATABASE_ROUTERS = (
    'django_tenants.routers.TenantSyncRouter',
)

# Password validation
# https://docs.djangoproject.com/en/5.0/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.0/topics/i18n/
LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.0/howto/static-files/
STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/5.0/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
PUBLIC_DOMAIN = 'localhost:8000'
ADMIN_URL = 'admin/'