runtime: nodejs14  # Or the Node.js version you're using

env: standard

entrypoint: node app.js  # Start the Node.js app

automatic_scaling:
  target_cpu_utilization: 0.65
  max_instances: 3

# Define environment variables
env_variables:
  NODE_ENV: 'production'  # Set the environment to production
  PORT: 8080  # Google App Engine uses port 8080

# Secrets manager variables
beta_settings:
  MONGO_URI: "projects/annadialogflow/secrets/MONGO_URI/versions/latest"  # MongoDB URI from Secret Manager

handlers:
  # Serve static files (React build)
  - url: /static
    static_dir: client/build/static

  # API routes
  - url: /api/.*
    script: auto

  # Auth routes
  - url: /auth/.*
    script: auto

  # Admin routes
  - url: /admin/.*
    script: auto

  # User routes
  - url: /user/.*
    script: auto

  # Catch-all route to serve React's index.html (for React SPA routing)
  - url: /.*
    static_files: client/build/index.html
    upload: client/build/index.html
