runtime: python312

entrypoint: gunicorn -b :$PORT backend.wsgi

handlers:
  - url: /static
    static_dir: static

env_variables:
  DJANGO_SETTINGS_MODULE: "backend.settings"
  # Add any additional environment variables here
