# Generated by Django 5.0.7 on 2024-07-31 02:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='school_add',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='user',
            name='school',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_auth.school'),
        ),
        migrations.AlterModelTable(
            name='school',
            table='schools',
        ),
    ]
