# Generated by Django 5.0.7 on 2024-10-16 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0002_conversation_grade_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conversation',
            name='grade_level',
        ),
    ]
