# Generated by Django 5.0.7 on 2024-08-04 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0005_alter_school_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schools', to='custom_auth.client'),
        ),
    ]
