# Generated by Django 5.0.7 on 2024-08-05 01:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0006_alter_school_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='custom_auth.client'),
        ),
    ]
