# Generated by Django 5.0.7 on 2024-10-07 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0008_userprofile_age_userprofile_artistic_score_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(max_length=20)),
                ('strand', models.CharField(max_length=255)),
                ('riasec_code', models.JSONField()),
                ('riasec_course_recommendation', models.JSONField()),
                ('strand_course_recommendation', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='recommended_courses',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
