# Generated by Django 5.0.7 on 2024-10-10 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0009_conversation_userprofile_recommended_courses'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('guidance', 'Guidance')], default='student', max_length=10),
        ),
    ]
