# Generated by Django 5.0.7 on 2024-10-13 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom_auth', '0011_conversation_artistic_score_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='has_agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='has_agreed_to_terms',
            field=models.BooleanField(default=False),
        ),
    ]
